interface CandidateApprovalBadgeProps {
  status: string;
  forecastApproved: boolean;
  reviewStatus: string | null;
  autoGenerated?: boolean;
}

export default function CandidateApprovalBadge({
  status,
  forecastApproved,
  reviewStatus,
  autoGenerated = true,
}: CandidateApprovalBadgeProps) {
  if (autoGenerated === false) {
    return (
      <span className="px-2 py-1 rounded border border-indigo-800/50 bg-indigo-950/30 text-indigo-300 text-xs font-mono">
        human-authored
      </span>
    );
  }

  if (forecastApproved || status === 'testing') {
    return (
      <span className="px-2 py-1 rounded border border-green-800/50 bg-green-950/30 text-green-300 text-xs font-mono">
        forecast-active
      </span>
    );
  }

  if (reviewStatus === 'approved') {
    return (
      <span className="px-2 py-1 rounded border border-green-800/50 bg-green-950/30 text-green-300 text-xs font-mono">
        approved
      </span>
    );
  }

  if (reviewStatus === 'rejected' || status === 'rejected') {
    return (
      <span className="px-2 py-1 rounded border border-rose-800/50 bg-rose-950/30 text-rose-300 text-xs font-mono">
        rejected
      </span>
    );
  }

  if (reviewStatus === 'needs_more_data' || status === 'needs_more_data') {
    return (
      <span className="px-2 py-1 rounded border border-sky-800/50 bg-sky-950/30 text-sky-300 text-xs font-mono">
        needs more data
      </span>
    );
  }

  if (status === 'ready_for_review' || status === 'proposed' || reviewStatus === 'pending') {
    return (
      <span className="px-2 py-1 rounded border border-amber-800/50 bg-amber-950/30 text-amber-300 text-xs font-mono">
        awaiting review
      </span>
    );
  }

  return (
    <span className="px-2 py-1 rounded border border-gray-700 bg-gray-800/40 text-gray-300 text-xs font-mono">
      auto-generated
    </span>
  );
}
